### ISSUE TITLE
unexpected result

### ISSUE THREAD

**Issue by tungcua66** [lerkoah/spa-on-python#1]
Hello, i downloaded your code to read the spa file, and when i print it, the result is not the same as csv file.
Are you sure your code is correct? And, how can you get to know the spa format file to read?
You can have file to test in the [link.](https://drive.google.com/drive/folders/1YW39JO1sz7_Pmla7-x8xUenKyfk5rhpb?usp=sharing)

**Comment by lerkoah** [comment]
Hello!

I tested agains LoadSpectra from matlab and the results are the same. Actually, my groundtruth was the outputs of LoadSpecta.

However, I plotted my output and the csv. In despite of wavelengths, the curves are close to each other. In this examples I plotting the results without wavelengths. I think that the problem are the wavelengths.

![image](https://user-images.githubusercontent.com/24939031/117027469-b8e02280-acca-11eb-9c31-4f953d84bb1c.png)

When I open your spa with a text editor, you can read the wavenumbers in 1/cm:

``
	 Aufl�sung:	 2,000 from 359,6647 to 3999,7034
``
That's means 2000 points between 359.667 to 3999.7034. Then I think the wavelengths in your csv might are in another units.

Regards,
Lerko.

**Comment by lerkoah** [comment]
Hi,

I confirmed my suspicion, now I'm plotting my results and your results in the wavenumbers (1/cm) and the curves are overlapping.

![image](https://user-images.githubusercontent.com/24939031/117031857-fa72cc80-acce-11eb-8942-9458693d5f1c.png)


I hope it helps you!

**Comment by tungcua66** [comment]
Well, that's strange. I use your function to loadSPA and i dont have the same graph like you.
![spectrum](https://user-images.githubusercontent.com/14801548/117309776-08694e80-ae83-11eb-97bc-8f9f5f8c541a.PNG)

**Comment by lerkoah** [comment]
Dear Tung,

The function is LoadSPAInterferogram? I think that you are using the function of [ZGainsforth ](https://gist.github.com/ZGainsforth/7b05bf0b0409ae57ce7f) and not my implementation. (Outputs looks similar and the namefunction is the same).

Can you clone my project and try again?
Thanks,
Lerko.

**Comment by tungcua66** [comment]
Hello, 
I reopen your project and give it a look and it work too well. Well many thanks to you genius.
