### ISSUE TITLE
Problem of drawing

### ISSUE THREAD

**Issue by tungcua66** [lerkoah/spa-on-python#2]
Hello, 
Sorry for bothering you again. Now im testing with the second test using always your function and it seems there is a problem here.
![problem of Y](https://user-images.githubusercontent.com/14801548/117321283-4a978d80-ae8d-11eb-91e7-2391b8eff1e6.PNG)
As you can see, the max Y = 0.9 while the Y in the graph is almost 6
I give you the test2.SPA and .csv to compare too. In this [link](https://drive.google.com/drive/folders/1YW39JO1sz7_Pmla7-x8xUenKyfk5rhpb?usp=sharing)
The graph of csv file will look like this:
![spec of csv test2](https://user-images.githubusercontent.com/14801548/117322131-05279000-ae8e-11eb-9cb2-93fdc47ed8d2.PNG)

**Comment by lerkoah** [comment]
Dear Tung,

No problem, I entertain myself by solving these problems. In my opinion, these are the data measurements. In my experience, in some case interferometer have artefacts/noise in low wavenumbers (high wavelength), regardless of the reading method.

I plot your csv and the spa data in the same figure.
![image](https://user-images.githubusercontent.com/24939031/117328319-84529f00-ae61-11eb-8949-934c5f1e88d2.png)

In the middle range the data is exactly the same. I uploaded to your folder an jupyter notebook the generate this figure.

I hope you it helps.

Regards,
Lerko

**Comment by tungcua66** [comment]
Hello, i will take a look at your jupyter, but what's that? ^.^

**Comment by lerkoah** [comment]
Sorry, Jupyter notebooks are is a web-based interactive computational environment for programming in python. But it's not necessary. You can run a traditional .py file:

```python
import pandas as pd
import matplotlib.pyplot as plt

from LoadSpectrum import read_spa

my_spectrum = read_spa('test2.SPA')
csv_spectrum = pd.read_csv('test2.CSV', sep=';', decimal=',', header=None)

plt.plot(1e7/my_spectrum[1], my_spectrum[0], label='read_spa')
plt.plot(csv_spectrum[0], csv_spectrum[1], label='csv')
plt.legend()

plt.xlabel('wavenumber [1/cm]')
plt.show()
```

**Comment by tungcua66** [comment]
Hello,
Sorry for late reply. I think i know what you wanna say. In fact, reading spa files directly will give the result more exact.
Now im trying to draw 3d dimention(a.plot(x, y, z)), by adding z = difference between date of files. I've modify your code, by returning only Spectra instead of "return Spectra, 1e7/Wavenumbers, SpectraTitles". The question is: why cant i draw by a.plot(spectra, deltaTime)? If spectra = read_spa(file.spa). I think i did not well understand your code.

**Comment by lerkoah** [comment]
Can you show the code? I think I have problems imaging your code.

However, if I understood, you want to make a 3d plot plotting x=spa_spectra and y=csv_spectra and z = spa_spectra - csv_spectra. I think the principal problem is spa and csv have diferent wavenumber's grid.

**Comment by tungcua66** [comment]
My code is very simple, normally if i wanna to read and draw spa file, i have 2 simple lines:
spectra = read_spa(file) #read_spa is your function, but i've modify to return spectra only
a.plot(spectra).
But now, i want to draw a 3d graph, so the 3rd dimention z= delta. I cant use a.plot(spectra, delta). What i dont understand here is in your code, the spectra is a list of coordinate x and y right? 
![Capture](https://user-images.githubusercontent.com/14801548/117846706-f8d27700-b281-11eb-85cc-5ff30adf621b.PNG)

**Comment by lerkoah** [comment]
Hi,

I have two problems with your code. First, for 3d plot, you need an special axis.

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
a = fig.add_subplot(111, projection='3d')
a.plot(x,y,z)
```

Second one, `spectra` is a onedimentional array with the absorbance values. Your problem seems to be that `z` is a one dimensional array, may be you are not computing properly your diference, I don't know the reason. Try printing you vector `z` or `z.shape`, it must be an array of shape `(3776, )`, if not print `x` and `y` (or `x.shape, y.shape`) to debugging.

**Comment by tungcua66** [comment]
Hello there, very happy to see your reply. Well maybe i need to declare z = [] and each time i have to z.append((y-x).total_seconds())    I want to ask if the problem comes from a.plot(spectra, z)? As you know, to draw 3d, we need x, y and z. With your function, we already have spectra but how can i retreive x and y from this "spectra"? I mean, as i understand, your spectra will be like: x1, x2, ...xn-y1, y2, ..., yn. Thats why we can draw it directly by a.plot(spectra)

**Comment by lerkoah** [comment]
It's easy,

My code returns
```python
return Spectra, 1e7/Wavenumbers, SpectraTitles
```

`Spectra` is `y`, `1e7/Wavenumbers` is `x`. Y think you can use:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

spectra, wavelength, title = read_spa(file)

z = ... # your Z

fig = plt.figure()
a = fig.add_subplot(111, projection='3d')
a.plot(x,y,z)

```

I hope it helps you!

**Comment by tungcua66** [comment]
If i write a.plot(x, y, z), the program will understand x and y?

**Comment by lerkoah** [comment]
Sorry, my mistake

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

spectra, wavelength, title = read_spa(file)

z = ... # your Z

fig = plt.figure()
a = fig.add_subplot(111, projection='3d')
a.plot(wavelength,spectra,z)
```

**Comment by tungcua66** [comment]
i will test and let you know if it's work. Thats very kind of you ^.^

**Comment by tungcua66** [comment]
Hello again, i've test but it shows error of wavelength, do you have any idea why? Thanks a lot
![Capture](https://user-images.githubusercontent.com/14801548/117965348-f411cf80-b322-11eb-97b9-9d1691e5cfdf.PNG)

**Comment by lerkoah** [comment]
Hello,

Probably you are using a old version of `LoadSpectrum.py`. I updated the code when you make the first question, because I found an incompatibility with recently numpy versions. Please, try to download the code again.

**Comment by tungcua66** [comment]
Hi there, well the updated version work pretty well with a.plot(wavelength,spectra,z) ^.^
![Capture](https://user-images.githubusercontent.com/14801548/118107422-02bdbc80-b3df-11eb-91b0-73e86b995785.PNG)
Now, i wanna rotate the figure, trying  a.plot(z, wavelength,spectra). And i have this error, do you know why?
![error](https://user-images.githubusercontent.com/14801548/118107784-7bbd1400-b3df-11eb-8390-d6dee6a79003.PNG)

**Comment by lerkoah** [comment]
probably you have problems with z shapes, try to print the shapes for understanding more:

```python
print('z shape', z.shape)
print('wavelength shape', wavelength.shape)
print('spectra shape', spectra.shape)
```

**Comment by tungcua66** [comment]
Hello, the holiday was a bit longer than expected ^^. Well today i've printed wavelength and spectra it return shape (3776,). And with z i got: print('z shape', z.shape)
AttributeError: 'float' object has no attribute 'shape'
If problem comes from z, why i can always a.plot(wavelength,spectra,z)?
Anyway here is my complete function(z is difference between date of each spa files in seconds
![Capture](https://user-images.githubusercontent.com/14801548/118490640-75e86b00-b71e-11eb-89db-9c8296a54eda.PNG)
)

**Comment by lerkoah** [comment]
Dear Tung,
Sorry for the delay of my answer, I have had a lot of work theses days.

The problem is that z it doesn't an array and you couldn't plot an array and and scalar... x,y,z must have the same dimension. Try to append in a dict all z in a list and then plot it.

Regards,
Lerko

**Comment by tungcua66** [comment]
I thought it should be the problem, but why it work when i have a.plot(wavelength, spectra, z)?

**Comment by lerkoah** [comment]
I think python is plotting z a "level" then basically a 2d plot but a diferent "z location"

**Comment by tungcua66** [comment]
yeah i think you are right, thanks a lot!

**Comment by tungcua66** [comment]
And btw, i know thats out of range, but i could not find solution on internet. I'm having 3 lists: for example a = [1, 2, 3], b = [1, 2, 3] and c = [1, 2, 3]. So, how can i combine them in one list : d = [a, b, c] = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]? i've tried "dstack" but it gives me d = [[ [1 1 1 ] [2 2 2] [3 3 3] ]] and d shape:  (1, 3, 3).

**Comment by lerkoah** [comment]
Hhaha Don't worry.

Usually those kind of problems you can solve using hstack (Horizontal Stack) or vstack (Vertical Stack). I think that you need to use `np.vstack`.

dstack probably is for Depth Stack.

Good luck!

**Comment by tungcua66** [comment]
Hello, 
Thank you for your reply, i found the solution, its np.stack(()) ^^. Btw, thanks to your readSPA function, i can progress very much my work.
